correct yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,9 +24,15 @@ jobs:
       - name: Check Output Directory
         run: ls -la ./out
 
-      - name: Install sshpass
-        run: sudo apt-get install -y sshpass
-
+      - name: Prepare DigitalOcean
+        uses: appleboy/ssh-action@v0.1.10
+        with:
+          host: 24.199.121.110
+          username: root
+          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
+          port: 22
+          run: rm -rf /var/www/career-path-api/*
+            
       - name: Add DigitalOcean Host to Known Hosts
         run: |
           mkdir -p ~/.ssh
@@ -44,10 +50,9 @@ jobs:
           username: root
           password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
           port: 22
-          debug: true
           script: |
             # Kill any running instance of the API
-            pkill -f "dotnet CareerPathCore.API.dll" || true
+            pkill -f "dotnet" || true
         
             # Start the new API instance with full detachment
             setsid nohup dotnet /var/www/career-path-api/CareerPathCore.API.dll > /var/www/career-path-api/app.log 2>&1 < /dev/null &
@@ -56,7 +61,7 @@ jobs:
             sleep 5
         
             # Check if the API process is running
-            pgrep -f "dotnet CareerPathCore.API.dll" > /dev/null && echo "API is running" || (echo "API failed to start" && exit 1)
+            pgrep -f "dotnet" > /dev/null && echo "API is running" || (echo "API failed to start" && exit 1)
         
             # Check if the application is listening on the correct port (e.g., 5000)
             netstat -tuln | grep 5000 || (echo "API is not listening on port 5000" && exit 1)
